org: fabiandinklage
app: tree-db-app
service: tree-mongodb-api
provider:
 name: aws
 runtime: nodejs10.x # set node.js runtime
 memorySize: 1024 # set the maximum memory of the Lambdas in Megabytes
 timeout: 120 # the timeout is 10 seconds (default is 6 seconds)
#  stage: dev # setting the env stage to dev, this will be visible in the routes
#  region: us-east-1
functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: trees # path will be domain.name.com/dev/trees
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: trees/{id} # path will be domain.name.com/dev/trees/1
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/trees
    events:
      - http:
          path: trees
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  getAllType:
    handler: handler.getAllType # path will be domain.name.com/dev/trees
    events:
      - http:
          path: trees/type/{type}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  countAllAge:
    handler: handler.countAllAge
    events:
      - http:
          path: trees/age/count/
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  getAllAgeLimited:
    handler: handler.getAllAgeLimited # path will be domain.name.com/dev/trees
    events:
      - http:
          path: trees/age/limited/
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  getAllAge:
    handler: handler.getAllAge # path will be domain.name.com/dev/trees
    events:
      - http:
          path: trees/age/
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  update:
    handler: handler.update # path will be domain.name.com/dev/trees/1
    events:
      - http:
          path: trees/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  delete:
    handler: handler.delete
    events:
      - http:
          path: trees/{id} # path will be domain.name.com/dev/trees/1
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation  